const ALL_VOCAB_DATA = {
    'liste_voc_1': {
        title: 'Liste voc 1',
        selectorId: 'listeVoc1Btn',
        subcategories: {
            'full_list': {
                name: 'Vocabulaire Complet',
                color: '#BB86FC',
                alert: null,
                data: [
    ["A wine merchant", "Un marchand de vin"],
    ["A poulterer", "Un volailler"],
    ["A fishmonger", "Un poissonnier"],
    ["A florist", "Un fleuriste"],
    ["A butcher", "Un boucher"],
    ["A launderer", "Un blanchisseur"],
    ["A furniture dealer", "Un marchand de meubles"],
    ["An antique dealer", "Un antiquaire"],
    ["A second-hand dealer", "Un brocanteur"],
    ["A hairdresser", "Un coiffeur"],
    ["An undertaker", "Un entrepreneur de pompes funèbres"],
    ["A worker, workman", "Un ouvrier"],
    ["A craftsman", "Un artisan"],
    ["A tailor", "Un couturier"],
    ["A painter", "Un peintre"],
    ["A plumber", "Un plombier"],
    ["A mason, a bricklayer", "Un maçon, un briquetier"],
    ["A plasterer", "Un plâtrier"],
    ["A glazier", "Un vitrier"],
    ["A joiner", "Un menuisier"],
    ["A blacksmith", "Un forgeron"],
    ["An electrician", "Un électricien"],
    ["A locksmith", "Un serrurier"],
    ["A shoemaker", "Un cordonnier"],
    ["A window cleaner", "Un laveur de vitre"],
    ["A postman", "Un facteur"],
    ["A foreman", "Un contremaître"],
    ["A policeman", "Un policier"],
    ["A dustman", "Un éboueur"],
    ["A gardener", "Un jardinier"],
    ["A gamekeeper", "Un garde-chasse"],
    ["A farmer", "Un fermier"],
    ["A waiter, a waitress", "Un serveur, une serveuse"],
    ["A barman, a barmaid", "Un(e) barman (-aid)"],
    ["A housemaid", "Une bonne"],
    ["A cook", "Un cuisinier, Cuisiner"],
    ["A mechanic", "Un mécanicien"],
    ["A guard", "Un gardien"],
    ["A warden", "Un gardien"],
    ["A driving-instructor", "Un moniteur d’auto-école"],
    ["A bus driver", "Un chauffeur de bus"],
    ["A lorry-driver", "Un chauffeur de camion"],
    ["A taxi-driver", "Un chauffeur de taxi"],
    ["A pickpocket", "Un voleur à la tire"],
    ["A controller", "Un contrôleur"],
    ["A furniture remover", "Un déménageur"],
    ["An inspector", "Un inspecteur"],
    ["A postman", "Un postier"],
    ["A detective", "Un détective"],
    ["A receptionist", "Un(e) réceptionniste"],
    ["A pilot", "Un pilote"],
    ["An air-hostess", "Une hôtesse de l’air"],
    ["A sailor", "Un marin"],
    ["A guide", "Un guide"],
    ["A photographer", "Un photographe"],
    ["A tax-collector", "Un percepteur"],
    ["A customs officer", "Un douanier"],
    ["A judge", "Un juge"],
    ["A lawyer, a barrister", "Un avocat"],
    ["A solicitor", "Un notaire"],
    ["A doctor", "Un médecin"],
    ["A surgeon", "Un chirurgien"],
    ["A chemist", "Un pharmacien"],
    ["A dentist", "Un dentiste"],
    ["An oculist", "Un oculiste"],
    ["A specialist", "Un spécialiste"],
    ["A scientist", "Un scientifique"],
    ["A vet", "Un vétérinaire"],
    ["A writer", "Un écrivain"],
    ["A playwright", "Un dramaturge"],
    ["An editor", "Un rédacteur en chef"],
    ["A printer", "Un imprimeur"],
    ["A journalist", "Un journaliste"],
    ["An artist", "Un artiste"],
    ["A musician", "Un musicien"],
    ["A conductor", "Un chef d’orchestre"],
    ["A singer", "Un chanteur"],
    ["An actor, an actress", "Un acteur, une actrice"],
    ["A dancer", "Un danseur"],
    ["A prompter", "Un souffleur"],
    ["A typist", "Une dactylo"],
    ["A clerk", "Un employé de bureau"],
    ["An engineer", "Un ingénieur"],
    ["An accountant", "Un comptable"],
    ["An executive", "Un cadre, un administrateur"],
    ["A manager", "Un directeur"],
    ["A CEO, Chief Executive Officer", "Un directeur général"],
    ["A politician", "Un homme politique"],
    ["A president", "Un président"],
    ["A colleague", "Un collègue"],
    ["A pal", "Un copain"],
    ["A workmate", "Un camarade de travail"],
    ["A rise", "Une augmentation"],
    ["The salary", "Le salaire"],
    ["The wages", "Les salaires, les gages"],
    ["The taxes", "Les impôts"],
    ["A trade-union", "Un syndicat"],
    ["A wage-earner", "Un salarié"],
    ["A strike", "Une grève"],
    ["To go on strike", "Se mettre en grève"],
    ["Social security", "La sécurité sociale"],
    ["NHS", "Sécurité sociale britannique"],
    ["Letter of application", "Lettre de motivation"],
    ["Job interview", "Entretien d’embauche"],
    ["Applicant", "Candidat"],
    ["Weakness", "Faiblesse"],
    ["Strength", "Force"],
    ["In your opinion", "Selon vous/toi"],
    ["Position", "Poste"],
    ["To waffle", "Baratiner, parler pour ne rien dire"],
    ["Concisely", "Succinctement, brièvement"],
    ["To stick to the point", "Ne pas s'éloigner du sujet"],
    ["Lack", "Manque"],
    ["Keenness", "Enthousiasme"],
    ["To graduate", "Être diplômé"],
    ["To embark on", "Se lancer dans, entreprendre"],
    ["To be keen to", "Avoir hâte de"],
    ["Team-player", "Personne qui a l'esprit d'équipe"],
    ["To gain experience", "Acquérir de l'expérience"],
    ["Field", "Domaine"],
    ["Personal details", "Données personnelles"],
    ["Employment", "Emploi, expérience professionnelle"],
    ["Skills", "Compétences"],
    ["Interests", "Intérêts, hobbys"],
    ["Proficient in", "Bonne maîtrise de"],
    ["Working", "Élémentaire, de base"],
    ["Knowledge", "Connaissance"],
    ["To apply for", "Postuler à"],
    ["Enclosed", "Ci-joint"],
    ["Extensive", "Approfondi"],
    ["To put into practice", "Mettre en pratique"],
    ["Convenience", "Convenance"],
    ["Jitters", "Frousse"],
    ["To sidetrack", "Détourner"],
    ["To jot down", "Noter, griffonner"],
    ["Neatly", "Soigneusement"],
    ["To give sb a hard time", "Donner du fil à retordre, en faire baver à qqn"],
    ["To giggle", "Glousser, rire bêtement"],
    ["To yawn", "Bâiller"],
    ["To ramble on", "Radoter"],
    ["Cocky", "Prétentieux"],
    ["Willing", "Prêt, disposé"],
    ["To retire", "Prendre sa retraite"],
    ["Retirement", "La retraite"],
    ["Wealth", "La richesse"],
    ["Poverty", "La pauvreté"],
    ["Labour legislation", "La législation du travail"],
    ["Benefit", "L'avantage"],
    ["Skilful", "Habile"],
    ["Clumsy", "Maladroit"],
    ["Unemployed", "Chômeur"],
    ["On the dole", "Au chômage"],
    ["Wealthy, rich", "Riche"],
    ["Poor, broke", "Pauvre, fauché"],
    ["To inherit", "Hériter"],
    ["To transfer", "Transférer"],
    ["To keep up with", "Se maintenir au niveau de"],
    ["To be busy", "Être occupé"],
    ["To practise", "S’entraîner"],
    ["To train", "S’entraîner"],
    ["To undertake", "Entreprendre"],
    ["To manage", "Gérer"],
    ["To decrease", "Diminuer"],
    ["To increase", "Augmenter"],
    ["To work overtime", "Faire des heures supplémentaires"],
    ["To earn money", "Gagner de l’argent"],
    ["To get a rise", "Avoir une augmentation"],
    ["To have a rise", "Avoir une augmentation"],
    ["To trust", "Avoir confiance"],
    ["To congratulate", "Féliciter"],
    ["To dismiss", "Congédier"],
    ["To resign", "Démissionner"],
    ["To pay taxes", "Payer des impôts"],
    ["To take a day off", "Prendre un jour de congé"],
    ["Does he have a trade?", "Exerce-t-il une profession?"],
    ["It opens the door to any career", "Cela ouvre la porte à n’importe quelle carrière"],
    ["Hands wanted", "On embauche"],
    ["They’re over-staffed", "Ils ont trop de personnel"],
    ["His boss has given him a week’s notice", "Son patron lui a donné un préavis d’une semaine"],
    ["I have earned it by the sweat of my brow", "Je l’ai gagné à la sueur de mon front"],
    ["He had an accident at work last month", "Il a eu un accident au travail le mois dernier"],
    ["He’d like to enjoy the fruits of his labour", "Il voudrait profiter du fruit de son labeur"],
    ["They should raise the minimum basic wage", "Ils devraient augmenter le salaire minimum"],
    ["They are rolling in it", "Ils roulent sur l’or"],
    ["He’s a bit short of money", "Il est un peu à court d’argent"],
    ["Don’t throw the money out the window", "Ne jette pas l’argent par les fenêtres"],
    ["They get starvation wages", "Ils ont des salaires de misère"],
    ["We’d better join a trade-union", "On ferait mieux de se syndiquer"],
    ["They’re going to stage a general strike", "Ils vont déclencher une grève générale"],
    ["He is on the dole", "Il est au chômage"],
    ["Are you sure he’ll get the old-age pension?", "Es-tu sûr qu’il touchera l’allocation vieillesse?"],
    ["Fortunately, they draw family allowances", "Heureusement, ils touchent des allocations familiales"],
    ["A shopkeeper", "Un commerçant"],
    ["A baker", "Un boulanger"],
    ["A confectioner", "Un confiseur"],
    ["A grocer", "Un épicier"],
    ["A greengrocer", "Un marchand de légumes"],
    ["A dairyman, a milkman", "Un laitier"],
    ["A caterer", "Un traiteur"],
    ["A bookseller", "Un libraire"],
    ["A jeweller", "Un bijoutier"],
    ["A sculptor", "Un sculpteur"],
    ["A fireman", "Un pompier"],
    ["To cook", "Cuisiner"],
    ["A civil servant", "Un fonctionnaire"],
    ["A nurse", "Une infirmière"],
    ["A skilled worker", "Un ouvrier spécialisé"],
    ["To sweat", "Transpirer"],
    ["To develop", "Développer"],
    ["They aren't rolling on it", "Ils ne roulent pas sur l'or"]
]
            }
        }
    },
    'voc_note': {
        title: 'voc → note',
        selectorId: 'vocNoteBtn',
        subcategories: {
            'full_list': {
                name: 'Vocabulaire Complet',
                color: '#4CAF50',
                alert: null,
                data: [
    ["to mow the lawn", "tondre la pelouse"],
    ["a mower", "la tondeuse"],
    ["grocery bagger", "personne qui emballe les achats à l'épicerie"],
    ["lifeguard", "maître nageur"],
    ["on the side", "sur le coté"],
    ["law office Runner", "cabinet → message de cabinet juridique (assistant)"],
    ["camp counselor (Anglais américain)", "animateur dans un camp"],
    ["movie theatre attendant (Anglais américain)", "ouvreur/ouvreuse/gardien(ne) de cinéma"],
    ["referee", "arbitre"],
    ["high pressure", "beaucoup de pression"],
    ["an animal Shelter associate", "collaborateur dans un refuge animal (pour animaux)"],
    ["car valet", "voiturier"],
    ["to be stuck inside", "être coincé à l'intérieur"],
    ["to flip burgers", "retourner des hamburgers"],
    ["to scoop ice cream", "faire, servir des boules de glace"],
    ["to collect ticket", "récupérer, ramasser les tickets"],
    ["to get yelled at", "se faire hurler dessus"],
    ["insane", "fou, insensé"],
    ["to get hired", "être engagé"],
    ["wealthy", "riche, aisé"],
    ["to work minimum -wage -gigs", "avoir des petits boulots, toucher le salaire minimum"],
    ["to look on the bright side", "voir le bon coté des choses"],
    ["a lifetime", "toute une vie"],
    ["a slacker", "un fainéant"],
    ["pricey", "cher, coûteux"],
    ["to work shifts", "travailler à pause, faire des pauses"],
    ["a backyard", "la cour/un jardin"],
    ["water slide", "un toboggan aquatique"],
    ["to be graduated", "être diplômé"],
    ["in order to", "afin de"],
    ["to rate", "évaluer, estimer, coter"],
    ["benefits", "les avantages"],
    ["seasonal", "saisonnier"],
    ["to relive", "revivre"],
    ["Cinderella", "Cendrillon"],
    ["Snow white", "Blanche Neige"],
    ["Rapunzel", "Raiponce"],
    ["team player", "esprit d'équipe"],
    ["rewarding", "gratifiant, enrichissant"],
    ["Go for it!", "Fonce, Vas-y"],
    ["to land the job", "décrocher un emploi"],
    ["the process", "le processus, le développement"],
    ["job hunting", "rechercheur d'emploi"],
    ["dedicated about", "dévoué, passionné"],
    ["to boost", "stimuler, accroître"],
    ["academic", "universitaire"],
    ["career plan", "plan de carrière, projet professionnelle"],
    ["skills", "compétences"],
    ["job interview", "entretien d'embauche"],
    ["to apply for a job", "postuler"],
    ["to come across", "croiser (qqn)"],
    ["a full-time job =/ a part-time job", "un temps plein =/ un temps partielle"],
    ["When the time comes", "quand le moment arrivera"],
    ["to cope with / to handle / to deal with", "gérer, affronter, supporter"],
    ["it is unlikely", "peu probable"],
    ["There is no denying", "on ne peut pas nier"],
    ["to bounce back", "rebondir"],
    ["to soar", "monter en flèche, jaillir, grandir"],
    ["self-esteem", "l'estime de soi"],
    ["to save", "épargner"],
    ["to stick with", "rester, s'en tenir à"],
    ["to reach a goal", "atteindre un objectif"],
    ["important to", "important de"],
    ["to work smth out", "élaborer, trouver une solution"],
    ["to start your ownn buisness important", "important → de"],
    ["to work out", "élaboration, terminer une évaluation"],
    ["to stand your own business", "lancer sa propre affaire"],
    ["to pass by", "passer devant"],
    ["to submit an application", "poser sa candidature"],
    ["wacky", "déjanter"],
    ["to be worth", "en valoir la peine"],
    ["to face competition", "affronter la concurrence"],
    ["the word is out that", "il paraît que / on dit que"],
    ["to gain experience", "gagner de l'expérience"],
    ["the bottom line", "l'argument ultime"],
    ["to do one's duty", "accomplir sa tâche, son devoir"],
    ["geeky", "coincé"],
    ["the making off", "la fabrication, réalisation"],
    ["a taste of", "un aperçu de"],
    ["dull", "terne, fade, sombre"],
    ["faced", "confronté"],
    ["the pace", "le rythme, l'allure, la cadence"],
    ["opportunities", "les chances, les occasions"],
    ["to provide", "fournir"],
    ["to learn the ropes", "s'intégrer, faire son apprentissage"],
    ["challenging", "stimulants / exigeant"],
    ["exciting", "passionnant"],
    ["to volunteer", "se porter volontaire, faire du bénévolat"],
    ["to fill (out) a form", "remplir un formulaire"],
    ["abilities", "les capacités"],
    ["salary / wage", "le salaire"],
    ["not mind + verb-ing", "ne pas gêner de"],
    ["to browse", "naviguer, parcourir (internet)"],
    ["an ad / advert / advertisement", "la publicité, l'annonce"],
    ["stay true to yourself", "reste fidèle à toi-même"],
    ["lunch coupons", "check repas"],
    ["to be decent", "être convenable (avoir un niveau correct)"],
    ["to be proud of", "être passionné de"],
    ["I'm keen on + verb-ing", "être intéressé par"],
    ["efficient", "efficace"],
    ["to be picky", "être difficile, pointilleux"],
    ["dazzling", "étourdissant, fulgurant, éclatant"],
    ["an amusement park", "un parc d'attraction"],
    ["a wardrobe", "garde robe (chez soi) / vestiaire (soirée, etc...)"],
    ["ride operator", "un opérateur d'attractions"],
    ["landscaper", "un paysagiste"],
    ["catering", "service traiteur"],
    ["food store", "stand de nourriture"],
    ["to last", "durer"],
    ["I'll put you through", "je vous passe... (au téléphone)"],
    ["Please hold", "restez en ligne (au téléphone)"],
    ["to make an appointment", "prendre rendez-vous"],
    ["definitely", "absolument, vraiment, définitivement"],
    ["an asset", "un atout"],
    ["to suit", "convenir"],
    ["a diary", "un agenda"],
    ["a job vacancy", "un poste vacant"],
    ["unexpected", "inattendu"],
    ["to tutor", "donner des cours particuliers"],
    ["problem solver", "orienté solution"],
    ["a kitchen hand", "un commis (aide cuisinier)"],
    ["grumpy", "grincheux"],
    ["to do paperwork", "faire de l'administratif"]
]
            }
        }
    }
};